version: '3.8'

services:
  app:
    image: searchengine:v1
    build:
      context: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=jdbc:postgresql
      - DB_PORT=//db:5432
      - SCHEMA_NAME=search_engine
      - DB_USERNAME=postgres
      - DB_USER_PASSWORD=testtest

  db:
    image: postgres:14.5-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testtest
      - POSTGRES_DB=search_engine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d search_engine -U postgres"]
      retries: 10
      timeout: 5s