spring.datasource.url: ${DB_HOST}:${DB_PORT}/${SCHEMA_NAME}
spring.datasource.username: ${DB_USERNAME}
spring.datasource.password: ${DB_USER_PASSWORD}
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size: 100
spring.jpa.properties.hibernate.order_inserts: true
spring.liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

sites:
  - url: https://www.playback.ru
    name: Playback
  - url: https://www.nikoartgallery.com
    name: Nikoartgallery

user-agent: HeliontSearchBot
