spring:
  datasource:
    url: ${DB_HOST:jdbc:postgresql}:${DB_PORT://localhost:5432}/${SCHEMA_NAME:search_engine}
    username: ${DB_USERNAME:postgres}
    password: ${DB_USER_PASSWORD:testtest}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml


elasticsearch:
  uri: ${ELASTICSEARCH_URI:localhost:9200}

sites:
  - url: https://www.playback.ru
    name: Playback

user-agent: HeliontSearchBot
