spring.datasource.url: jdbc:mysql://localhost:3306/search_engine
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.jdbc.batch_size: 100
spring.jpa.properties.hibernate.order_inserts: true

sites:
  - url: https://www.playback.ru
    name: Playback
  - url: https://www.nikoartgallery.com
    name: Nikoartgallery

user-agent: HeliontSearchBot
